# python:3.8-alpine 으로하면 requirements.txt 에있는 특정 한두개의 파이썬 패키지 설치하면서 에러남
FROM python:3.8.12-slim-buster

# .pyc 생성 방지
ENV PYTHONDONTWRITEBYTECODE 1
# 로그 즉시 출력
ENV PYTHONUNBUFFERED 1


WORKDIR /app

COPY ./requirements.txt .

# RUN apk update \
#   && apk add --virtual build-deps gcc python3-dev musl-dev \
#   && apk add --no-cache mariadb-dev zlib-dev jpeg-dev libffi-dev


RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get -yq install python3-dev default-libmysqlclient-dev build-essential \
  && pip3 install --upgrade pip setuptools \
  && pip install -r requirements.txt

COPY . .
